### ISSUE TITLE
Does not work on raspberry pi

### ISSUE THREAD

**Issue by sprintel** [groggyegg/plugin.video.dramacool#11]
This addon works on my firestick kodi 18 but keeps throwing an error when I try to play it on my raspberry pi 3 (libreelec kodi 18). It keeps telling me to check the error log. Anyone has the same issue? Below is the error messages from the log:

NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'AsianLoadResolver' object has no attribute 'net'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.dramacool/resources/lib/addon.py", line 298, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.dramacool/resources/lib/plugin.py", line 48, in run
                                                redirect(pathquery)
                                              File "/storage/.kodi/addons/plugin.video.dramacool/resources/lib/plugin.py", line 25, in redirect
                                                function(**match.groupdict())
                                              File "/storage/.kodi/addons/plugin.video.dramacool/resources/lib/addon.py", line 260, in _
                                                url = resolveurl.resolve(serverlist[position])
                                              File "/storage/.kodi/addons/script.module.resolveurl/lib/resolveurl/__init__.py", line 131, in resolve
                                                return source.resolve()
                                              File "/storage/.kodi/addons/script.module.resolveurl/lib/resolveurl/hmf.py", line 186, in resolve
                                                stream_url = resolver.get_media_url(self._host, self._media_id)
                                              File "/storage/.kodi/addons/plugin.video.dramacool/resources/lib/resolveurl/plugins/asianload.py", line 32, in get_media_url
                                                html = self.net.http_GET(self.get_url(host, media_id), headers=headers).content
                                            AttributeError: 'AsianLoadResolver' object has no attribute 'net'

Any help is greatly appreciated.

**Comment by groggyegg** [comment]
It seems to be a problem related to script.module.resolveurl. Do you know which version of resolveurl you are using? And does other mirror works?

I haven't found any issue so far with my raspberry pi 3.

**Comment by sprintel** [comment]
Thanks for the tip. I updated the resolveurl addon from 5.0.38 to 5.1.34 and it’s working now.
