### ISSUE TITLE
Ubuntu 20.04 / Kodi Matrix 19.1

### ISSUE THREAD

**Issue by GoldenPandora** [groggyegg/plugin.video.dramacool#16]
This is a new problem as I haven't been able to find a solution from Google searches.  On 6/30/2021, Kodi / Dramacool was working perfectly and I was able to watch a few shows. I made a system update to Ubuntu. Everything worked in Kodi, except for Dramacool. I have been uninstalling and installing this add on, rebooting the system then checked the Kodi log file.

Sorry for the wall of text below, but I wonder if you have an idea what the problem might be.

**EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'PosixPath' object has no attribute 'startswith'
                                                   Traceback (most recent call last):
                                                     File "/usr/lib/python3.8/pkgutil.py", line 415, in get_importer
                                                       importer = sys.path_importer_cache[path_item]
                                                   KeyError: PosixPath('/home/anitabe/.kodi/addons/plugin.video.dramacool/resources/lib/request')
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/anitabe/.kodi/addons/plugin.video.dramacool/resources/lib/addon.py", line 6, in <module>
                                                       import idb
                                                     File "/home/anitabe/.kodi/addons/plugin.video.dramacool/resources/lib/idb.py", line 2, in <module>
                                                       import request
                                                     File "/home/anitabe/.kodi/addons/plugin.video.dramacool/resources/lib/request/__init__.py", line 49, in <module>
                                                       for module_info in iter_modules([Path(__file__).parent]):
                                                     File "/usr/lib/python3.8/pkgutil.py", line 129, in iter_modules
                                                       for i in importers:
                                                     File "/usr/lib/python3.8/pkgutil.py", line 419, in get_importer
                                                       importer = path_hook(path_item)
                                                     File "<frozen importlib._bootstrap_external>", line 1594, in path_hook_for_FileFinder
                                                     File "<frozen importlib._bootstrap_external>", line 1469, in __init__
                                                     File "<frozen importlib._bootstrap_external>", line 177, in _path_isabs
                                                   AttributeError: 'PosixPath' object has no attribute 'startswith'
                                                   -->End of Python script error report<--
                                                   
2021-07-02 14:05:00.233 T:3127     INFO <general>: Python interpreter stopped
2021-07-02 14:05:00.240 T:3126    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.dramacool/
2021-07-02 14:05:00.245 T:3035    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dramacool/) failed**

There are more error messages on other lines, but the text is identical. A kodi.zip file has been attached.
Hope you can help.
[kodi.zip](https://github.com/groggyegg/plugin.video.dramacool/files/6756755/kodi.zip)

**Comment by groggyegg** [comment]
Are you installing Kodi from ppa:team-xbmc/ppa? It seems to be an issue with python version.

**Comment by GoldenPandora** [comment]
Yes. Am I using the wrong version of Kodi? Everything was working fine
until the Ubuntu system update.
Unfortunately, I don't know what was updated, and that's when the problems
with Kodi / Dramacool started.
What version of python is Dramacool compatible with?

Thank you for your response.

**Comment by groggyegg** [comment]
It's the correct version. In Windows, the python library are included in the installation, should be the same for Ubuntu. You could try to reinstall the Kodi.

I have tested in Ubuntu 20.04 and have not noticed any issue with the addon.

**Comment by GoldenPandora** [comment]
Okay, I'll look into it and reinstall Kodi.

Thank you.

**Comment by groggyegg** [comment]
I have removed the code that is causing this issue. Try update to the latest and see if the problem still exist.

**Comment by GoldenPandora** [comment]
Hello,

Everything is working fine now! Thank you so very much.
