### ISSUE TITLE
Dramacool not working

### ISSUE THREAD

**Issue by stvg88** [groggyegg/plugin.video.dramacool#24]
Hi groggyegg,

I've been using Dramacool addon for awhile, and all was working normally until few days ago, when I suddenly cannot browse any titles anymore. I can only see the main category list of (Search Drama, Search Star, etc.), but when clicking in, it just leads to an error. You can find the log below.

````
2022-03-03 05:02:15.887 T:10920   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.ConnectionError'>
                                                   Error Contents: HTTPSConnectionPool(host='watchasian.so', port=443): Max retries exceeded with url: /category/korean-drama (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CDF7D97C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
                                                   Traceback (most recent call last):
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connection.py", line 169, in _new_conn
                                                       conn = connection.create_connection(
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\util\connection.py", line 96, in create_connection
                                                       raise err
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\util\connection.py", line 86, in create_connection
                                                       sock.connect(sa)
                                                   ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 699, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 382, in _make_request
                                                       self._validate_conn(conn)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 1010, in _validate_conn
                                                       conn.connect()
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connection.py", line 353, in connect
                                                       conn = self._new_conn()
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connection.py", line 181, in _new_conn
                                                       raise NewConnectionError(
                                                   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001CDF7D97C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 755, in urlopen
                                                       retries = retries.increment(
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\util\retry.py", line 574, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='watchasian.so', port=443): Max retries exceeded with url: /category/korean-drama (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CDF7D97C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.dramacool\resources\lib\addon.py", line 322, in <module>
                                                       plugin.run()
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.dramacool\resources\lib\plugin.py", line 51, in run
                                                       function(**kwargs)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.dramacool\resources\lib\addon.py", line 166, in _
                                                       charlist, statuslist, yearlist = request.parse(plugin.path, FilterListParser)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.dramacool\resources\lib\request\__init__.py", line 55, in parse
                                                       return parser(**kwargs).parse(get(path))
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.dramacool\resources\lib\request\__init__.py", line 48, in get
                                                       response = _session.get(f'https://{subdomain}{domain}{path}')
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 555, in get
                                                       return self.request('GET', url, **kwargs)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 516, in send
                                                       raise ConnectionError(e, request=request)
                                                   requests.exceptions.ConnectionError: HTTPSConnectionPool(host='watchasian.so', port=443): Max retries exceeded with url: /category/korean-drama (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CDF7D97C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
                                                   -->End of Python script error report<--
````

**Comment by groggyegg** [comment]
Thanks for the log. Might be because of domain change. Will do a quick commit and if the issue still exists then I will work with it during the weekend.
