### ISSUE TITLE
Drama List Error

### ISSUE THREAD

**Issue by megazone23** [groggyegg/plugin.video.dramacool#61]
**Describe the bug**

**To Reproduce**
1. Go to 'Drama List'
2. Click on 'Korean'
3. Click on 'Year'
4. Click on '2023'
5. Click on 'OK'
6. Results in 'DramaCool Error'

**Expected behavior**
A list of shows matching the selected search criteria

**Log file**
2023-07-16 16:57:15.266 T:30548   error <general>: Repository add-on repository.universalscrapers does not have any directory and won't be able to update/serve addons! Please fix the addon.xml definition
2023-07-16 16:57:18.438 T:14692   error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2023-07-16 16:57:23.566 T:32688    info <general>: [script.module.xbmcext] Routing "/drama"
2023-07-16 16:57:23.567 T:32688    info <general>: [script.module.xbmcext] Calling "drama"
2023-07-16 16:57:31.016 T:34364    info <general>: [script.module.xbmcext] Routing "/category/korean-drama"
2023-07-16 16:57:31.017 T:34364    info <general>: [script.module.xbmcext] Calling "drama_filter"
2023-07-16 16:57:31.033 T:14692    info <general>: Loading skin file: C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.xbmcext\.\resources\skins\Default\1080i\MultiSelectTabDialog.xml, load type: LOAD_ON_GUI_INIT
2023-07-16 16:57:42.990 T:34364    info <general>: [script.module.xbmcext] Routing "/category/korean-drama/[]/[]/[]/["2023"]"
2023-07-16 16:57:42.991 T:34364    info <general>: [script.module.xbmcext] Calling "drama_list"
2023-07-16 16:57:43.000 T:34364   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'e' is not defined
                                                   Traceback (most recent call last):
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.peewee\.\peewee.py", line 3237, in execute_sql
                                                       cursor.execute(sql, params or ())
                                                   sqlite3.OperationalError: ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\plugin.video.dramacool\dramacool\addon.py", line 243, in drama_list
                                                       RecentFilter.insert(path=plugin.path, title=plugin.path).on_conflict(
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.peewee\.\peewee.py", line 1962, in inner
                                                       return method(self, database, *args, **kwargs)
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.peewee\.\peewee.py", line 2033, in execute
                                                       return self._execute(database)
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.peewee\.\peewee.py", line 2838, in _execute
                                                       return super(Insert, self)._execute(database)
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.peewee\.\peewee.py", line 2551, in _execute
                                                       cursor = database.execute(self)
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.peewee\.\peewee.py", line 3250, in execute
                                                       return self.execute_sql(sql, params, commit=commit)
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.peewee\.\peewee.py", line 3244, in execute_sql
                                                       self.commit()
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.peewee\.\peewee.py", line 3010, in __exit__
                                                       reraise(new_type, new_type(exc_value, *exc_args), traceback)
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.peewee\.\peewee.py", line 192, in reraise
                                                       raise value.with_traceback(tb)
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.peewee\.\peewee.py", line 3237, in execute_sql
                                                       cursor.execute(sql, params or ())
                                                   peewee.OperationalError: ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\plugin.video.dramacool\dramacool\addon.py", line 359, in <module>
                                                       plugin()
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.xbmcext\.\xbmcext\__init__.py", line 489, in __call__
                                                       function(**kwargs)
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\plugin.video.dramacool\dramacool\addon.py", line 222, in drama_filter
                                                       plugin.redirect(f'{plugin.path}/{characters}/{genres}/{statuses}/{years}')
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.xbmcext\.\xbmcext\__init__.py", line 586, in redirect
                                                       self()
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\script.module.xbmcext\.\xbmcext\__init__.py", line 489, in __call__
                                                       function(**kwargs)
                                                     File "C:\Users\rk609048\AppData\Roaming\Kodi\addons\plugin.video.dramacool\dramacool\addon.py", line 245, in drama_list
                                                       except e:
                                                   NameError: name 'e' is not defined
                                                   -->End of Python script error report<--
                                                   
2023-07-16 16:57:43.003 T:28312    info <general>: CActiveAESink::OpenSink - initialize sink
2023-07-16 16:57:43.152 T:24832   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.dramacool/category/korean-drama
2023-07-16 16:57:43.163 T:14692   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dramacool/category/korean-drama) failed

**Additional context**

**Comment by groggyegg** [comment]
This might be an issue with the database due to recent change in table. A workaround is to remove the old database file in userdata.

**Comment by megazone23** [comment]
I reinstalled the addon and that corrected the problem.
