### ISSUE TITLE
Unable to update to Version 2.0.0

### ISSUE THREAD

**Issue by AcidSlide** [groggyegg/plugin.video.dramacool#7]
Hi there,

Before anything, super love your plugin for kodi.  This is the only plugin I use to watch kdramas.  Anyway, i've got 2 kodi installations and both are unable to update to Version 2.0.0.  It's getting errors related to xbmc.python

![image](https://user-images.githubusercontent.com/6833047/105927994-163b5680-6080-11eb-86fc-cd7fa2d631a9.png)

I hope this gets fixed without having to reinstall the it.

**Comment by groggyegg** [comment]
If you are not using Kodi 19 then ignore the message or disable auto-update for the addon. This is because the update is for Kodi 19 which is expected to be release soon. Kodi 19 will have python 3 which is not compatible with older python. I won't add support for that so the addon for Kodi 18 or lower will have its end in version 1.8.X (it's still functioning, but no new features will be added).

My recommendation is to upgrade to Kodi 19 when it's officially released. Just keep in mind that older addons won't work if support for python 3 has not been added.

I will leave this issue open so other people will know it.

**Comment by rainbatt** [comment]
Where can I download the previous version?  Thanks.  Have to reinstall Kodi 18.9.

**Comment by groggyegg** [comment]
> Where can I download the previous version? Thanks. Have to reinstall Kodi 18.9.

You can find it in the link below

[groggyegg.github.io](https://github.com/groggyegg/groggyegg.github.io)

**Comment by NayemAhmedNiloy** [comment]
𝚟𝚎𝚛𝚜𝚒𝚘𝚗 𝟸.𝟶.𝟶 𝚠𝚘𝚛𝚔𝚜 𝚙𝚎𝚛𝚏𝚎𝚌𝚝𝚕𝚢 𝚘𝚗 𝙺𝚘𝚍𝚒 𝚟𝟷𝟿. 𝙹𝚞𝚜𝚝 𝚞𝚙𝚍𝚊𝚝𝚎 𝚢𝚘𝚞𝚛 𝚔𝚘𝚍𝚒 𝚊𝚙𝚙 𝚝𝚘 𝚟𝚎𝚛𝚜𝚒𝚘𝚗 𝟷𝟿 𝚊𝚗𝚍 𝚒𝚝 𝚠𝚒𝚕𝚕 𝚠𝚘𝚛𝚔 𝚜𝚖𝚘𝚘𝚝𝚑𝚕𝚢.
𝙸𝚏 𝚔𝚘𝚍𝚒 𝚟𝚎𝚛𝚜𝚒𝚘𝚗 𝟷𝟿 𝚒𝚜 𝚗𝚘𝚝 𝚊𝚟𝚊𝚒𝚕𝚊𝚋𝚕𝚎 𝚒𝚗 𝚢𝚘𝚞𝚛 𝚌𝚘𝚞𝚗𝚝𝚛𝚢 𝚝𝚑𝚎𝚗 𝚌𝚘𝚗𝚗𝚎𝚌𝚝 𝚊 𝚜𝚎𝚌𝚞𝚛𝚎 𝚟𝚙𝚗 𝚊𝚗𝚍 𝚕𝚘𝚐𝚒𝚗 𝚝𝚘 𝚙𝚕𝚊𝚢𝚜𝚝𝚘𝚛𝚎 𝚠𝚒𝚝𝚑 𝚊𝚗𝚘𝚝𝚑𝚎𝚛 𝚐𝚘𝚘𝚐𝚕𝚎 𝚒𝚍.

**Comment by AcidSlide** [comment]
> 𝚟𝚎𝚛𝚜𝚒𝚘𝚗 𝟸.𝟶.𝟶 𝚠𝚘𝚛𝚔𝚜 𝚙𝚎𝚛𝚏𝚎𝚌𝚝𝚕𝚢 𝚘𝚗 𝙺𝚘𝚍𝚒 𝚟𝟷𝟿. 𝙹𝚞𝚜𝚝 𝚞𝚙𝚍𝚊𝚝𝚎 𝚢𝚘𝚞𝚛 𝚔𝚘𝚍𝚒 𝚊𝚙𝚙 𝚝𝚘 𝚟𝚎𝚛𝚜𝚒𝚘𝚗 𝟷𝟿 𝚊𝚗𝚍 𝚒𝚝 𝚠𝚒𝚕𝚕 𝚠𝚘𝚛𝚔 𝚜𝚖𝚘𝚘𝚝𝚑𝚕𝚢.
> 𝙸𝚏 𝚔𝚘𝚍𝚒 𝚟𝚎𝚛𝚜𝚒𝚘𝚗 𝟷𝟿 𝚒𝚜 𝚗𝚘𝚝 𝚊𝚟𝚊𝚒𝚕𝚊𝚋𝚕𝚎 𝚒𝚗 𝚢𝚘𝚞𝚛 𝚌𝚘𝚞𝚗𝚝𝚛𝚢 𝚝𝚑𝚎𝚗 𝚌𝚘𝚗𝚗𝚎𝚌𝚝 𝚊 𝚜𝚎𝚌𝚞𝚛𝚎 𝚟𝚙𝚗 𝚊𝚗𝚍 𝚕𝚘𝚐𝚒𝚗 𝚝𝚘 𝚙𝚕𝚊𝚢𝚜𝚝𝚘𝚛𝚎 𝚠𝚒𝚝𝚑 𝚊𝚗𝚘𝚝𝚑𝚎𝚛 𝚐𝚘𝚘𝚐𝚕𝚎 𝚒𝚍.

it won't work on my android tv box, it has a custom kodi build for it's hardware which is still using kodi 18.x base codes.  And I'm not sure if they maker of the box will release an updated version that is using kodi 19.x

**Comment by NayemAhmedNiloy** [comment]
_i see. that's why it won't update to version 2.0.0. Just use the previous version and ignore updates until your tv box can update kodi to the latest version. _

**Comment by groggyegg** [comment]
@AcidSlide Support for Kodi 18 has been added in v3.0.0.

**Comment by AcidSlide** [comment]
@groggyegg Wow, thanks for this!

**Comment by AcidSlide** [comment]
@groggyegg Version 3.0.0 has no issues when using with Kodi 19.x (my other instllations), but after trying it on the Android TV Box using Kodi 18.x, i'm encountering this error:

```
2022-05-18 14:03:16.281 T:10501   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
                                              'The soupsieve package is not installed. CSS selectors cannot be used.'
2022-05-18 14:03:17.297 T:10514   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.openweathermap.maps/default.py", line 189, in run
                                                self.merge_tiles()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.openweathermap.maps/default.py", line 250, in merge_tiles
                                                out.paste( tile, (imx, imy), tile.convert('RGBA') )
                                              File "/data/user/0/org.xbmc.kodi/cache/apk/assets/addons/script.module.pil/lib/PIL/Image.py", line 833, in convert
                                                self.load()
                                              File "/data/user/0/org.xbmc.kodi/cache/apk/assets/addons/script.module.pil/lib/PIL/ImageFile.py", line 195, in load
                                                seek(o)
                                            IOError: [Errno 22] Invalid argument
```

This has happens after selecting a playable server (for example StreamSB).
